version: 2.1
orbs:
  codecov: codecov/codecov@1.1.1

jobs:
  build:
    docker:
      - image: circleci/node:10.20.1
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies with Yarn
          command: yarn
      - save_cache:
          key: npm-cache-v1-{{ checksum "yarn.lock" }}
          paths:
            - /home/circleci/.npm
  test:
    docker:
      - image: circleci/node:10.20.1
    steps:
      - run:
          name: Run tests with coverage
          command: yarn run test
      - codecov/upload:
          file: {{ coverage_report_filepath }}
